global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'dean-orchestrator'
    static_configs:
      - targets: ['orchestrator:8082']
    metrics_path: '/metrics'
    
  - job_name: 'dean-postgres'
    static_configs:
      - targets: ['postgres-prod:5432']
      
  - job_name: 'dean-redis'
    static_configs:
      - targets: ['redis-prod:6379']
      
  - job_name: 'dean-nginx'
    static_configs:
      - targets: ['nginx:80']
      
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
      
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']