# docker-compose.security.yml
# Security overrides for production deployment
version: '3.8'

services:
  postgres:
    environment:
      POSTGRES_PASSWORD: c=Fz;?J4Z~.T;+g^K68n.@q^S<>7Jpw]
      POSTGRES_USER: dean_admin
      POSTGRES_DB: agent_evolution
    
  redis:
    command: redis-server --requirepass ,;x3vfBP(}0jT02#X^suKQ>.
    
  dean-orchestration:
    environment:
      DEAN_ENV: production
      DEAN_SERVICE_API_KEY: dean_service_fXgyw4yK-3YTt3hIKzP7_gPzbeEIlZV8LMEVNNEQlGbs6K85VSkfpti_8yG6Xwk2
      DEAN_JWT_SECRET_KEY: ZHzWSl3a3A8UFaUL4EgSK2teHYx4JFrDjXO1PqIhtE3_gsioPeigUbB3k8OHt3LULUGE8O6fRg0eRec7vc8QXQ
    
  airflow-webserver:
    environment:
      AIRFLOW__CORE__FERNET_KEY: i2me4zLcZkir9ou/Flv2/7dMFhnnMF6uMxDZH5qsJsc=
      AIRFLOW__WEBSERVER__SECRET_KEY: guZ8-Mpc03BuxrhWEKtO9JGp5Fxh3985WY1AbOby5Vh28MPmZqtgNC7MySwHaS7_tLP--_mwI0rsO5b40N0YRA
      AIRFLOW_ADMIN_PASSWORD: ~h,flQn+#4ey&hsJ!t&D&O&L
